name: flutter_pos_printer_platform_image_3
description: A flutter plugin for POS thermal printers via USB and TCP/Ethernet. Supports ESC/POS and TSPL command protocols on Android, iOS, and Windows.
version: 2.0.0
homepage: https://github.com/cactus-do/flutter_pos_printer_platform

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  image_v3: ^3.3.0
  network_info_plus: ^4.0.2
  ping_discover_network_forked: ^0.0.1
  dart_snmp: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: do.cactus.flutter_pos_printer_platform
        pluginClass: FlutterPosPrinterPlatformPlugin
      ios:
        pluginClass: FlutterPosPrinterPlatformPlugin
      windows:
        pluginClass: FlutterPosPrinterPlatformPlugin
